Simple NumPy exercises

In this task you are practicing using NumPy in several applications.

## Task 1. Theoretical Part

В **обязательном** порядке пройдитесь по задачам на kaggle и прорешайте сами 

https://www.kaggle.com/code/themlphdstudent/learn-numpy-numpy-50-exercises-and-solution

## Task 2. Power of a matrix

Write a function that would take in a matrix and a non-negative integer,
check for that matrix is square, and return the power of the matrix computed through
successive multiplication.

In [117]:
import numpy as np
import copy
def matrix_power(mtrx,n=1):
    # Write your code here
    if n == 1:
        return mtrx
    if n < 0:
        raise ValueError("Power can't be a negative number")
    if len(mtrx[0]) == len(mtrx):
        result = copy.deepcopy(mtrx)
        new_matrix = copy.deepcopy(mtrx)
        for p in range(n-1):
            for i in range(len(mtrx)):
                for j in range(len(mtrx[i])):
                    row = mtrx[i]
                    column = [new_matrix[k][j] for k in range(len(mtrx))]
                    some = [row[l]*column[l] for l in range(len(row))]
                    result[i][j] = sum(some)
            new_matrix = copy.deepcopy(result)
        return result

A = np.array([[1,2,0],[0,2,3],[1,1,5]])
print(matrix_power(A,3))

[[  7  20  48]
 [ 24  41 126]
 [ 34  58 167]]


Here are the tests to pass for your code (which are referred to as *unit tests*)

In [118]:
# Test the code above
# you can read this section about try and except 
# https://education.yandex.ru/handbook/python/article/model-isklyuchenij-python-try-except-else-finally-moduli

A = np.array([[1,2,0],[0,2,3],[1,1,5]])
B = [[355,614,1806],[903,1565,4533],[1210,2113,6098]]
eq=np.equal(matrix_power(A,5),B)
if eq.all():
    print('Test 1 passed')
else:
    print('Test 1 FAIL')


A = [[1,2,0],[0,2,3],[1,1,5]]
B = [[355,614,1806],[903,1565,4533],[1210,2113,6098]]
eq=np.equal(matrix_power(A,5),B)
if eq.all():
    print('Test 2 passed')
else:
    print('Test 2 FAIL')


try:
    matrix_power([1],4.5)
except TypeError:
    print('Test 3 passed')
except:
    print('Test 3 FAIL')
else:
    print('Test 3 FAIL')

try:
    matrix_power([1],-5)
except ValueError:
    print('Test 4 passed')
except:
    print('Test 4 FAIL')
else:
    print('Test 4 FAIL')

Test 1 passed
Test 2 passed
Test 3 passed
Test 4 passed


## Task 2. Autoregressive model in matrix form

Consider the AR(1) model

$$
y_t = a y_{t-1} + \varepsilon, \; \varepsilon \sim N(0, 1).
$$

We can represent it in the form

$$
Ay = \varepsilon \quad \quad \varepsilon \sim N(0, 1)
$$

where $ A $ is

$$
A = \begin{bmatrix} 1  & 0 & \cdots & 0 & 0  \cr
                      -a  & 1 & \cdots & 0 & 0 \cr
                      \vdots & \vdots & \cdots & \vdots & \vdots \cr
                      \vdots & \vdots & \cdots & 1 & 0 \cr
                      0 & 0 & \cdots & -a & 1 \end{bmatrix}
$$

and $ y $ and $ \varepsilon $ are $ (T x 1) $ vectors

Generate an AR(1) series with $ T=500 $ and $ \alpha = 0.9 $
using matrix algebra, and make a plot of $ y_t $.

Hint: use NumPy.eye() with additional arguments.

In [3]:
# replace @@@ by your code
import numpy as np

T = 500
α = 0.9
ɛ = np.random.randn(T)
A = np.eye(T)
for i in range(1,len(A)):
    A[i][i-1] = -α
print(A)
y = np.linalg.inv(A) @ ɛ 
A = -α * np.eye(500, )
print(A)
# import matplotlib.pyplot as plt
# plt.figure(figsize=(15, 5))
# plt.plot(y)
# plt.grid()
# plt.show()

[[ 1.   0.   0.  ...  0.   0.   0. ]
 [-0.9  1.   0.  ...  0.   0.   0. ]
 [ 0.  -0.9  1.  ...  0.   0.   0. ]
 ...
 [ 0.   0.   0.  ...  1.   0.   0. ]
 [ 0.   0.   0.  ... -0.9  1.   0. ]
 [ 0.   0.   0.  ...  0.  -0.9  1. ]]
[[-0.9 -0.  -0.  ... -0.  -0.  -0. ]
 [-0.  -0.9 -0.  ... -0.  -0.  -0. ]
 [-0.  -0.  -0.9 ... -0.  -0.  -0. ]
 ...
 [-0.  -0.  -0.  ... -0.9 -0.  -0. ]
 [-0.  -0.  -0.  ... -0.  -0.9 -0. ]
 [-0.  -0.  -0.  ... -0.  -0.  -0.9]]
